### ISSUE TITLE
[1.2.2] Docking ports wont dock at certain orientations

### ISSUE THREAD

**Issue by Qwarkk6** [linuxgurugamer/TweakableEverything#1]
At certain orientations (of 90°) the docking ports wont dock together. There isn't any capture torque or anything either. Removing tweakableEverything makes it possible to dock the ports together.

**Comment by linuxgurugamer** [comment]
Report by forfa:

All I want is the ability to attach things to a node on the shielded docking ports in the VAB/SPH.  I installed TweakableEverything along with ToadicusTools after deleting everything except TweakableDockingNode.cfg and TweakableDockingNode.dll.  Nodes in VAB/SPH are now activated, great!  There are also seven additional tweakable sliders in VAB/SPH - Max Capture Roll Angle, Max Acquire Roll Angle, Acquire Range - Force - Torque, Ejection Force, and Re-engage Distance.  The tweakable sliders for the last five are no big deal.  Default seems to be the same as stock, seems to make no difference in flight vs stock, I'm happy to just ignore those.  

The problem is related to Max Capture Roll Angle.  In flight, when docking having left the slider for this (and Acquire Angle) at its default 90, docking behavior is drastically changed vs stock.  I bring a ship's docking port close to the target docking port, magnetic acquire force activates and attracts the ships together, as normal.  But then they don't dock: they come into contact, there remains an attractive force holding them loosely together, but docking doesn't occur until I carefully rotate the ship so the docking port's native orientation is 90 degrees to the target port's native orientation.  

And man oh man, it is sensitive.  90.1 or 89.9 degrees won't dock.  That level of precision sometimes is just not achievable with the ships I'm flying, where the port may be very far from the center of mass and off-axis.  Secondly that 90 degree orientation is rarely the one I want - this often means SSTO tails breaking solar panels or colliding with the target vessel, in my case.

IMO the default behavior should be same-as-stock: no restriction on docking angle, on all docking ports everywhere.  Perhaps I can change a value in VAB before launch, but:

#1 I don't want to add more things on a build checklist I didn't ask for
#2 Once you launch it can't be changed. If you have an existing game with vessels in flight, you install the mod for the design element, now your already-launched vessels may be literally unable to dock with each other
So I'd like one of the solutions here:

A. Self-modify the code to disable the rotation angle element
B. Use an additional Module Manager script to override the default setting on the rotation angle element to effectively disable it (without having to change it manually each and every time - and have it applied to ships already in flight)
C. Point out that this might not be the intended behavior, and might be considered a bug?
